quarkus.datasource.db-kind = postgresql 

%prod.quarkus.datasource.username = hibernate
%prod.quarkus.datasource.password = hibernate
%prod.quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/veille-techno-back
%prod.quarkus.hibernate-orm.schema-management.strategy=create