quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=update

# mp.jwt.verify.publickey.location=publicKey.pem  # magie magie
# mp.jwt.verify.issuer=https://example.com/issuer 

# quarkus.native.resources.includes=publicKey.pem 